services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: development-user
      POSTGRES_PASSWORD: development-password
      POSTGRES_DB: db
    volumes:
      - postgres-storage:/var/lib/postgresql/data
  adminer:
    image: michalhosna/adminer:4.8.1-en_v1
    ports:
      - "3001:8080"
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: development-user
      ADMINER_PASSWORD: development-password
      ADMINER_DB: db
      ADMINER_AUTOLOGIN: 1
    links: 
      - postgres:postgres
    depends_on:
      - postgres
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "25:1025"
      - "3002:8025"
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z.fips
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "3003:9001"
    environment:
      MINIO_ROOT_USER: development-user
      MINIO_ROOT_PASSWORD: development-password
    volumes:
      - minio-storage:/data

volumes:
  postgres-storage: ~
  minio-storage: ~
